all:
	echo "type *make clean* to delete temporary files"
clean: clean_files clean_directories custom
clean_files:
	rm -f config.yaml multiqc_config.yaml slurm*out stats.txt unlock.sh schema.yaml fastqc.sh fastqc.rules ./Makefile
clean_directories:
	rm -rf .snakemake
custom:
	
